services:
    - type: web
      name: ipt-final-2025-frontend
      buildCommand: npm ci && npm run build
      staticPublishPath: ./dist
      envVars:
          - key: NODE_VERSION
            value: 18
      routes:
          - type: rewrite
            source: /*
            destination: /index.html
