services:
    - type: web
      name: spa
      buildCommand: npm run build
      staticPublishPath: ./dist
      envVars:
          - key: NODE_VERSION
            value: 18.x
      routes:
          - type: rewrite
            source: /*
            destination: /index.html
